# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9ae6f7b1acf8df0de5e342f99b90e3d3b7c60771ce5484c206a00a6c6b01188bed150501e5c181aa20c9c0ecefac0ea9c5902a6d927ba54b8c0d124de5008b6

test:
  secret_key_base: 6b1bda364148756fc8d29b1248329af7f0d86a7d266256e188068f70783bf9902dacdc175be76b59f78c43e7ac632376cda2d6ae1b84197407351bbb1950b874

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
